src/java/cl/duoc/model/Clientes.java
    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.model;

/**
 *
 * @author Grupo 1
 */
public class Clientes {

    private String rutCliente;
    private String usuarioEmpresa;
    private String password;
    private String nombreCliente;
    private int telefono;
    private String direccion;
    
    
    public Clientes(String rutCliente, String usuarioEmpresa, String password, String nombreCliente, int telefono, String direccion) {
        this.rutCliente = rutCliente;
        this.usuarioEmpresa = usuarioEmpresa;
        this.password = password;
        this.nombreCliente = nombreCliente;
        this.telefono = telefono;
        this.direccion = direccion;
    }

    public Clientes() {
    }

    public String getRutCliente() {
        return rutCliente;
    }

    public void setRutCliente(String rutCliente) {
        this.rutCliente = rutCliente;
    }

    public String getUsuarioEmpresa() {
        return usuarioEmpresa;
    }

    public void setUsuarioEmpresa(String usuarioEmpresa) {
        this.usuarioEmpresa = usuarioEmpresa;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNombreCliente() {
        return nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    public int getTelefono() {
        return telefono;
    }

    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Override
    public String toString() {
        return "Clientes{" + "rutCliente=" + rutCliente + ", usuarioEmpresa=" + usuarioEmpresa + ", password=" + password + ", nombreCliente=" + nombreCliente + ", telefono=" + telefono + ", direccion=" + direccion + '}';
    }

    
    
}

src/java/cl/duoc/model/OrdenesCompra.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.model;

/**
 *
 * @author Grupo 1
 */
public class OrdenesCompra {

    private int numeroOrden;
    private String detalleOrden;
    private Clientes ClientesRutCliente;
    
    public OrdenesCompra() {
    }

    public OrdenesCompra(int numeroOrden, String detalleOrden, Clientes ClientesRutCliente) {
        this.numeroOrden = numeroOrden;
        this.detalleOrden = detalleOrden;
        this.ClientesRutCliente = ClientesRutCliente;
    }

    public int getNumeroOrden() {
        return numeroOrden;
    }

    public void setNumeroOrden(int numeroOrden) {
        this.numeroOrden = numeroOrden;
    }

    public String getDetalleOrden() {
        return detalleOrden;
    }

    public void setDetalleOrden(String detalleOrden) {
        this.detalleOrden = detalleOrden;
    }

    public Clientes getClientesRutCliente() {
        return ClientesRutCliente;
    }

    public void setClientesRutCliente(Clientes ClientesRutCliente) {
        this.ClientesRutCliente = ClientesRutCliente;
    }

    @Override
    public String toString() {
        return "OrdenesCompra{" + "numeroOrden=" + numeroOrden + ", detalleOrden=" + detalleOrden + ", ClientesRutCliente=" + ClientesRutCliente + '}';
    }
    

    
}

src/java/cl/duoc/servlet/InicioClienteServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.servlet;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Brian
 */
public class InicioClienteServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/cl/duoc/servlet/ListarHabitacionesServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.duoc.servlet;

import cl.duoc.model.Habitaciones;
import cl.duoc.model.Proveedores;
import cl.duoc.negocio.HabitacionesNegocio;
import cl.duoc.negocio.ProveedorNegocio;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author fenix
 */
public class ListarHabitacionesServlet extends HttpServlet {

     private static final Logger LOGGER = Logger.getLogger(ProveedoresServlet.class.getName());
     HabitacionesNegocio negocio;
     
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        HttpSession session = request.getSession();
        negocio = new HabitacionesNegocio();
        LOGGER.info("VALIDATE");
        try {  
            List<Habitaciones> dhabitaciones = negocio.listarTodo();
            LOGGER.info("listado: " + dhabitaciones.size());
            session.setAttribute("lista", dhabitaciones);
            response.sendRedirect("jsp/cliente/listar-habitaciones.jsp"); 

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}

web/jsp/cliente/buscar-factura.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
        <style>
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
        </style>
    </head>
    <body>       
    <jsp:include page="../template/navbar.jsp"/>            

        <div class="container mt-4" >

                <h1>Factura Emitidas</h1>
                
                <br>                
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>N° Factura</th>
                        <th>Precio</th>
                        <th>Rut Cliente</th>
                    </tr>
                </thead>
                <c:forEach items="${lista}" var="p" >
                    <tbody> 
                        <tr>
                            <td><input type="text" value="${p.numeroFactura}"/></td>
                            <td><input type="text" value="${p.precioFactura}"/></td>
                            <td><input type="text" value="${p.clientesRutCliente.rutCliente}"/></td>
                        </tr>   
                    </tbody>
                </c:forEach>
            </table>
				   							
            <div class="form-group">
                <div class="form-group mx-sm-3">
                    <button type="button" class="btn btn-primary">Imprimir</button>
                </div>
             </div>

        </div>
    </body>
</html>

web/jsp/cliente/inicio-cliente.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
    </head>
    <body>

        <jsp:include page="../template/navbar.jsp"/>



        <div class="container mt-4" >

            <div class="row row-cols-1 row-cols-md-4">
                <div class="col mb-3">
                    <div class="card h-100">
                        <img  src="${pageContext.request.contextPath}/img/registrar_cliente.png" height="180" width="180" style="margin-left: 35px; margin-right: 25px; margin-top: 25px;">
                        <div class="card-body">
                            <br>
                            <h5 class="card-title" style="text-align: center;" >Mi perfil</h5>
                            <p class="card-text"></p>
                            <a href="${pageContext.request.contextPath}/jsp/cliente/mantenedor-clientes.jsp" class="btn btn-outline-primary btn-block" style="text-align: center" > Entrar </a>
                        </div>
                    </div>
                </div>
                <div class="col mb-3">
                    <div class="card h-100">
                        <img  src="${pageContext.request.contextPath}/img/mantenedor_habitaciones.png" height="180" width="180" style="margin-left: 35px; margin-right: 25px; margin-top: 25px;">
                        <div class="card-body">
                            <br>
                            <h5 class="card-title" style="text-align: center;">Listar Habitaciones</h5>
                            <p class="card-text"></p>
                            <a href="${pageContext.request.contextPath}/listar-habitaciones-servlet" class="btn btn-primary btn-block" style="text-align: center" > Entrar </a>
                        </div>
                    </div>
                </div>
                <div class="col mb-3">
                    <div class="card h-100">
                        <img  src="${pageContext.request.contextPath}/img/servicio-comedor.jpg" height="180" width="180" style="margin-left: 35px; margin-right: 25px; margin-top: 25px;" >
                        <div class="card-body">
                            <br>
                            <h5 class="card-title" style="text-align: center;">Servicio Comedor</h5>
                            <p class="card-text"></p>
                            <a href="${pageContext.request.contextPath}/listar-servicio" class="btn btn-outline-primary btn-block" style="text-align: center" > Entrar </a>
                        </div>
                    </div>
                </div>
                <div class="col mb-3">
                    <div class="card h-100">
                        <img  src="${pageContext.request.contextPath}/img/factura.jpg" height="180" width="180" style="margin-left: 35px; margin-right: 25px; margin-top: 25px;">
                        <div class="card-body">
                            <br>
                            <h5 class="card-title" style="text-align: center;">Factura</h5>
                            <p class="card-text"></p>
                            <a href="${pageContext.request.contextPath}/factura-servlet" class="btn btn-outline-primary btn-block" style="text-align: center" > Entrar </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card" style="width: 16rem;">
                <div class="card h-100">
                    <img  src="${pageContext.request.contextPath}/img/mantenedor-orden-compra.jpg" height="180" width="180" style="margin-left: 35px; margin-right: 25px; margin-top: 25px;">
                    <div class="card-body">
                        <br>
                        <h5 class="card-title" style="text-align: center;">Orden de Compra</h5>
                        <p class="card-text"></p>
                        <a href="${pageContext.request.contextPath}/orden-compra" class="btn btn-outline-primary btn-block" style="margin-left: 15px;" > Entrar </a>
                    </div>
                </div>
            </div>



    </body>
</html>

web/jsp/cliente/listar-habitaciones.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
        <style>
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
        </style>
    </head>
    <body>       
        <jsp:include page="../template/navbar.jsp"/>            
       
        <div class="container" >
             <h1>Listado de Habitaciones</h1>
            <div class="row row-cols-1 row-cols-md-4">
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>N° habitacion</th>
                            <th>Tipo Cama</th>
                            <th>Accesorio</th>
                            <th>Precio</th>
                            <th>Cantidad Accesorios</th>                          
                          <!--  <th>Estado Habitacion</th> -->
                        </tr>
                    </thead>
                    <c:forEach items="${lista}" var="p" >
                        <tbody>
                            <tr>
                                <td><input type="text" value="${p.numeroHabitacion}"/></td>
                                <td><input type="text" value="${p.tipoCama}"/></td>
                                <td><input type="text" value="${p.accesorio}"/></td>
                                <td><input type="text" value="${p.precio}"/></td>
                                <td><input type="text" value="${p.cantidadAccesorios}"/></td>                              
                            </tr>
                        </tbody>
                    </c:forEach>
                </table>
            </div>
        </div>
    </body>
</html>

web/jsp/cliente/listar-servicio.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
        <style>
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
        </style>
    </head>
    <body>       
        <jsp:include page="../template/navbar.jsp"/>            

        <div class="container mt-4" >
            <h1>Listar Servicios</h1>
            <br>              
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>Nombre Plato</th>
                            <th>Precio</th>
                            <th>Dia</th>
                            <th>Detalle</th>
                            <th>Servicio</th>
                        </tr>
                    </thead>
                    <c:forEach items="${lista}" var="p" >
                        <tbody> 
                            <tr>
                                <td><input type="text" value="${p.nombrePlato}"/></td>
                                <td><input type="text" value="${p.precio}"/></td>
                                <td><input type="text" value="${p.minutasIdminuta.dia}"/></td>
                                <td><input type="text" value="${p.minutasIdminuta.detalleDia}"/></td>
                                <td><input type="text" value="${p.servicioComedorIdComedor.tipoServicio}"/></td>
                            </tr>
                        </tbody>
                    </c:forEach>
                </table>
        </div>
    </div>
</body>
</html>

web/jsp/cliente/mantenedor-clientes.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
        <style>
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
        </style>
    </head>
    <body>       
        <jsp:include page="../template/navbar.jsp"/>            
        <h1>Modulo Cliente</h1>
        <div class="container mt-4" >

            <form> 
                <br>

                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-2 col-form-label">
                        <h6><span class="col-lg-2 control-label">Rut</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="colFormLabel" placeholder="" disabled>
                    </div>
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Nombre de Usuario</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="colFormLabel" placeholder="" disabled>
                    </div>
                </div>

                <br>

                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-2 col-form-label">
                        <h6><span class="col-lg-2 control-label">Password</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="colFormLabel" placeholder="" disabled >
                    </div>
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Nombre Completo</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="colFormLabel" placeholder="Ingrese su nombre completo"  >
                    </div>
                </div>
                
                <br>
                
                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-2 col-form-label">
                        <h6><span class="col-lg-2 control-label">Telefono</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="colFormLabel" maxlength="9"  placeholder="ingrese su numero 9XXXXXXXX" >
                    </div>                   
                </div>
                
                <br>
                
                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-2 col-form-label">
                        <h6><span class="col-lg-2 control-label">Direccion</span></h6>
                    </label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="colFormLabel" maxlength="50"  placeholder="ingrese su direccion" >
                    </div>                   
                </div>


                <div class="form-group ">
                        <button type="button" class="btn" style="background-color: #f0b810; color: white;">Modificar</button>
                        <button type="button" class="btn" style="background-color: #f44336; color: white;" >Eliminar</button>
                </div>


                    
                </div>
            </form>
        </div>
    </div>
</body>
</html>

web/jsp/cliente/mantenedor-orden-compra.jsp
<%-- 
    Document   : Inicio_Cliente
    Created on : 18-05-2020, 5:11:06
    Author     : Brian
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <jsp:include page="../template/header.jsp"/>
        <style>
            h1 {text-align: center;}
            p {text-align: center;}
            div {text-align: center;}
        </style>
    </head>
    <body>       
        <jsp:include page="../template/navbar.jsp"/>            

        <div class="container mt-4" >

            <h1>Modulo Orden de Compra</h1>

            <form>

                <br> 

                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">N° de orden:</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="txt-numero-orden" placeholder="" >
                    </div>
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Rut Cliente</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="txt-rut-cliente" placeholder="" >
                    </div>
                </div>

                <div class="form-group row">

                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Rut Huesped</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="txt-rut-huesped" placeholder="" >
                    </div>
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Nombre Huesped</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="nombre-huesped" placeholder="" >
                    </div>
                </div> 

                <div class="form-group row">
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">Apellido Huesped</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="apellido-huesdped" placeholder="" >
                    </div>
                    <label for="colFormLabel" class="col-sm-3 col-form-label">
                        <h6><span class="col-lg-2 control-label">N° Habitacion</span></h6>
                    </label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" id="numero-habitacion" placeholder="" >
                    </div>
                </div>

                <br>

                <div class="form-group">
                    <div class="form-group mx-sm-3">
                        <button type="button" class="btn btn-success">Agregar Orden</button>
                    </div>
                </div>

            </form>
        </div>
        <section>
            <br>
            <h3 style="text-align: center;">Listado Proveedores</h3>

            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>N°de Orden</th>
                        <th>Rut Cliente</th>
                        <th>Rut Huesped</th>
                        <th>Nombre Huesped</th>
                        <th>Apellido Huesped </th>
                        <th>N° Habitacion</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <c:forEach items="${lista}" var="p" varStatus="i" >
                    <tbody> 
                        <tr>
                            <td><input type="text" id="txt-numero-orden-${i.count}" value="${p.ordenesCompraNumeroOrden.numeroOrden}" disabled="true" style="font-size: 10px !important" /></td>
                            <td><input type="text" id="txt-rut-cliente-${i.count}" value="${p.clientesRutCliente.rutCliente}" disabled="true" style="font-size: 10px !important"/></td>
                            <td><input type="text" id="txt-rut-huesped-${i.count}" value="${p.rutHuesped}" disabled="true" style="font-size: 10px !important"/></td>
                            <td><input type="text" id="txt-nombre-huesped-${i.count}" value="${p.nombreHuesped}" disabled="true" style="font-size: 10px !important"/></td>
                            <td><input type="text" id="txt-apellido-huesped-${i.count}" value="${p.apellidoHuesped}" disabled="true" style="font-size: 10px !important"/></td>
                            <td><input type="text" id="txt-numero-habitacion-${i.count}" value="${p.habitacionesIdHabitacion.txt_rut_cliente}" disabled="true" style="font-size: 10px !important"/></td>
                            <td>
                                <div class="form-inline">
                                    <button id="bnt-edit-${i.count}" type="button" onclick="edit('${i.count}')" class="btn btn-warning btn-sm">Modificar</button> 
                                    <button id="bnt-delete-${i.count}" type="button" onclick="deleteRow('${i.count}')" class="btn btn-danger btn-sm ">Eliminar</button>  
                                    <button id="bnt-save-${i.count}" type="button" onclick="saveRow('${i.count}')" class="btn btn-success btn-sm" hidden="true">Guardar</button>
                                    <button id="bnt-cancel-${i.count}" type="button" onclick="cancelRow('${i.count}')" class="btn btn-danger btn-sm" hidden="true">CANCEL</button>
                                </div>
                            </td>

                        </tr>
                    </tbody>
                </c:forEach>
            </table>
        </section>
    </body>
    
    <script>
        
         function edit(row) {


            editRow(row, false, false, false, false, false, false, true, true,
                    false, false);
        }

        function cancelRow(row) {
            editRow(row, true, true, true, true, true, true, false, false,
                    true, true);
        }

        function editRow(row, numeroOrdenDisabled, rutClienteDisabled,
                rutHuespedDisabled, nombreHuespedDisabled, apellidoHuespedDisabled, numeroHabitacionDisabled, 
                editDisabled, deleteDisabled, saveDisabled, cancelDisabled) {


            var txtNumeroOrden = "txt-numero-orden-" + row;
            var txtRutCliente = "txt-rut-cliente-" + row;
            var txtRutHuesped = "txt-rut-huesped-" + row;
            var txtNombreHuesped = "txt-nombre-huesped-" + row;
            var txtApellidoHuesped = "txt-apellido-huesped-" + row;
            var txtNumeroHabitacion = "txt-numero-habitacion-" + row;
            var btnEdit = 'bnt-edit-' + row;
            var btnDelete = 'bnt-delete-' + row;
            var btnSave = 'bnt-save-' + row;
            var btnCancel = 'bnt-cancel-' + row;

            document.getElementById(txtNumeroOrden).disabled = numeroOrdenDisabled;
            document.getElementById(txtRutCliente).disabled = rutClienteDisabled;
            document.getElementById(txtRutHuesped).disabled = rutHuespedDisabled;
            document.getElementById(txtNombreHuesped).disabled = nombreHuespedDisabled;
            document.getElementById(txtApellidoHuesped).disabled = apellidoHuespedDisabled;
            document.getElementById(txtNumeroHabitacion).disabled = numeroHabitacionDisabled;
            document.getElementById(btnEdit).hidden = editDisabled;
            document.getElementById(btnDelete).hidden = deleteDisabled;
            document.getElementById(btnSave).hidden = saveDisabled;
            document.getElementById(btnCancel).hidden = cancelDisabled;
        }

        function deleteRow(row) {
            var id = document.getElementById("txt-numero-orden-" + row).value;
            cancelRow(row);

            $.ajax({
                url: '${pageContext.request.contextPath}/DeleteOrdenCompraServlet?codigo=' + id,
                method: 'POST',
                success: window.location.reload()
            });

        }
        
        function saveRow(row) {

            var numero_orden = document.getElementById("txt-numero-orden-" + row).value;
            var rut_cliente = document.getElementById("txt-rut-cliente-" + row).value;
            var rut_huesped = document.getElementById("txt-rut-huesped-" + row).value;
            var nombre_huesped = document.getElementById("txt-nombre-huesped-" + row).value;
            var apellido_huesped = document.getElementById("txt-apellido-huesped-" + row).value;
            var numero_habitacion = document.getElementById("txt-numero-habitacion-" + row).value;
            
            cancelRow(row);
            const Http = new XMLHttpRequest();
            const url = '${pageContext.request.contextPath}/UpdateOrdenCompraServlet?numero_orden=' + numero_orden 
                    + '&rut_cliente=' + rut_cliente
                    + '&rut_huesped=' + rut_huesped + '&nombre_huesped=' + nombre_huesped
                    + '&apellido_huesped=' + apellido_huesped + '&numero_habitacion=' + numero_habitacion;
            Http.open('POST', url);
            Http.send();
        }
        
    </script>
    
</html>